In [ ]:
import tensorflow as tf
#enable eager execution (if not already enabled)
tf.config.run_functions_eagerly(True)

#define constant
a=tf.constant('hello world')
print(a.numpy())

b'hello world'


In [ ]:
import tensorflow as tf
a=tf.constant('hello world')
print(a)
b=tf.session()
print(b.run(a))
b.close()

In [ ]:
import tensorflow as tf
#scalar constant
a= tf.constant(42)
b=tf.constant(3.14)
c=tf.constant("hellow world")
print(a)
print(a.numpy())
print(b)
print(b.numpy())
print(c)
print(c.numpy())

tf.Tensor(42, shape=(), dtype=int32)
42
tf.Tensor(3.14, shape=(), dtype=float32)
3.14
tf.Tensor(b'hellow world', shape=(), dtype=string)
b'hellow world'


In [ ]:
#vector


a=tf.constant([1,2,3])
b=tf.constant([1.0,2.0,3.0])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [ ]:
a=tf.constant(([1,2],[3,4]))
print(a)
print(a.numpy())
b=tf.constant(([1.0,2.0],[3.0,4.0]))
print(b)
print(b.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]


In [ ]:
a=tf.constant([[1,2,3],[4,5,6],[7,8,9],[4,5,6]])
print(a)
print(a.numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]], shape=(4, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]


In [ ]:
#boolen constant
a=tf.constant(True)
print(a)
print(a.numpy())

tf.Tensor(True, shape=(), dtype=bool)
True


In [ ]:
#soecial characters
a=tf.zero(shape=(2,2))
print(a)
print(a.numpy())
b=tf.ones(shape=(3,3))
print(b)
print(b.numpy())

AttributeError: module 'tensorflow' has no attribute 'zero'

In [ ]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)
a=tf.constant(5.0)
b=tf.constant(3.0)
c=tf.multiply(a,b)
result=a*b
print(result)
print(result.numpy())

tf.Tensor(15.0, shape=(), dtype=float32)
15.0


In [ ]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[2,4],[5,6]])
print(a*b)
print((a*b).numpy())
print(tf.matmul(a,b))
print(a@b)


tf.Tensor(
[[ 2  8]
 [15 24]], shape=(2, 2), dtype=int32)
[[ 2  8]
 [15 24]]
tf.Tensor(
[[12 16]
 [26 36]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[12 16]
 [26 36]], shape=(2, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant(1.25)
print(a.numpy())


In [ ]:
import tensorflow as tf
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
e=tf.transpose(x)
print(e.numpy())
r=tf.reduce_sum(x)
print(e.numpy())
print(r.numpy())


[[1. 4.]
 [2. 5.]
 [3. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]
21.0


In [ ]:
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
j=x@tf.transpose(x)
c=tf.reduce

In [ ]:
#softmax function
log=tf.constant([30.,40.,50.,60.,70.])

softmax_probs=tf.nn.softmax(log,axis=0)
print(softmax_probs.numpy())

[4.248161e-18 9.357198e-14 2.061060e-09 4.539787e-05 9.999546e-01]


In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
data = pd.DataFrame({
    "Age": [25, 30, 35, 40, 45],
    "Height": [170, 175, 180, 185, 190],
    "Weight": [65, 70, 75, 80, 85],
    "Blood Pressure": [120, 125, 130, 135, 140]
})
X = data[["Age", "Height"]]
y = data["Blood Pressure"]
model = LinearRegression()
model.fit(X, y)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)
new_data = pd.DataFrame({"Age": [32], "Height": [182]})
predictions = model.predict(new_data)
print("Predicted Blood Pressure:", predictions[0])

Intercept: 22.499999999999957
Coefficients: [0.5 0.5]
Predicted Blood Pressure: 129.5


In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Example data: features (demographic info, medical history, treatment protocols) and outcomes
X = np.array([[1, 35, 120, 1], [0, 40, 130, 2], [1, 45, 140, 3]])
y = np.array([0, 1, 1])

# Create and fit the model
model = LinearRegression()
model.fit(X, y)

# Make predictions
new_patient = np.array([[1, 50, 150, 2]])
prediction = model.predict(new_patient)

print("Predicted outcome:", prediction)

Predicted outcome: [1.49206349]


In [ ]:
#text reading in whatsapp downloaded file
!pip install fpdf
from fpdf import FPDF
import pandas as pd
read=pd.read_fwf('/content/whatsapp.txt')
print(read)
read.to_csv("chat.csv")



    12/02/24, 10:39 am - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to  \
0    12/02/24, 10:37 am - Shanmukh (Cse-A) created ...                                                                                                     
1    12/02/24, 10:39 am - You joined using this gro...                                                                                                     
2    12/02/24, 10:39 am - +91 89199 94166 joined us...                                                                                                     
3    12/02/24, 10:39 am - +91 6304 408 513 joined u...                                                                                                     
4    12/02/24, 10:39 am - Abhi Ram VSVT (Cse-A) joi...                                                                                                     
..                                                 ...          

In [ ]:
from fpdf import FPDF
import pandas as pd

# Convert TXT to CSV
def txt_to_csv(input_file, output_file):
    # Read the text file into a DataFrame
    with open(input_file, 'r', encoding='utf-8') as file:
        content = file.readlines()
    df = pd.DataFrame(content, columns=['content'])

    # Write DataFrame to CSV
    df.to_csv(output_file, index=False)

# Convert CSV to PDF
def csv_to_pdf(input_file, output_file):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(input_file)

    # Create a PDF object
    pdf = FPDF()
    pdf.add_page()

    # Set font for the PDF
    pdf.set_font("Arial", size=12)

    # Add content from DataFrame to PDF
    for index, row in df.iterrows():
        # Convert Unicode characters to UTF-8 to avoid encoding errors
        content = row['content'].encode('latin-1', 'replace').decode('latin-1')
        pdf.cell(200, 10, txt=content, ln=True)

    # Save the PDF file
    pdf.output(output_file)

# Example usage
txt_to_csv("/content/whatsapp.txt", "/content/whatsapp.csv")
csv_to_pdf("/content/whatsapp.csv", "/content/whatsapp.pdf")